quriosity/urls.py
from django.conf.urls import url
from quriosity.views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^help/$', helpQ, name='help'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^details/$', details, name='details'),
    url(r'^question/(?P<qid>[0-9]{,2})/$', question, name='question'),
    url(r'^secret/$', allu, name='allu'),
    url(r'^res/$', res, name='res'),
    url(r'^winners/$', winners, name='winners'),
]

shilp16/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quriosity/', include('quriosity.urls')),
    url(r'^', include('website.urls')),
]

quriosity/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

class QUser(models.Model):
    name = models.CharField(_('name'), max_length=100)
    email = models.EmailField(_('email'), unique=True)
    phone = models.CharField(_('phone'), max_length=15)
    gender = models.CharField(_('gender'), max_length=5, blank=True, null=True)
    college = models.CharField(_('college'), max_length=50, blank=True, null=True)
    year = models.CharField(_('year'), max_length=5, blank=True, null=True)

    class Meta:
        verbose_name = _('quesr')
        verbose_name_plural = _('quesrs')

    def __unicode__(self):
        return self.name

class Question(models.Model):
    title = models.CharField(_('title'), max_length=30)
    content = models.TextField(_('content'))
    score = models.IntegerField(_('score'))
    answer = models.CharField(_('answer'), max_length=40)

    class Meta:
        verbose_name = _('Question')
        verbose_name_plural = _('Questions')

    def __unicode__(self):
        return self.title

class Team(models.Model):
    name = models.CharField(_('name'), max_length=30, unique=True)
    password = models.CharField(max_length=40)
    slot = models.IntegerField(default=1)
    members = models.ManyToManyField(QUser)
    response1 = models.CharField(max_length=25, default=0)
    response2 = models.CharField(max_length=25, default=0)
    response3 = models.CharField(max_length=25, default=0)
    response4 = models.CharField(max_length=25, default=0)
    response5 = models.CharField(max_length=25, default=0)
    response6 = models.CharField(max_length=25, default=0)
    response7 = models.CharField(max_length=25, default=0)
    response8 = models.CharField(max_length=25, default=0)
    response9 = models.CharField(max_length=25, default=0)
    response10 = models.CharField(max_length=25, default=0)
    response11 = models.CharField(max_length=25, default=0)
    response12 = models.CharField(max_length=25, default=0)
    response13 = models.CharField(max_length=25, default=0)
    response14 = models.CharField(max_length=25, default=0)
    response15 = models.CharField(max_length=25, default=0)

    class Meta:
        verbose_name = _('team')
        verbose_name_plural = _('teams')

    def __unicode__(self):
        return self.name

class Response(models.Model):
    response = models.CharField(_('response'), max_length=40)
    question = models.ForeignKey(Question)
    team = models.ForeignKey(Team)

    class Meta:
        verbose_name = _('Response')
        verbose_name_plural = _('Responses')

    def __unicode__(self):
        return self.team.name

class HelpQuestion(models.Model):
    name = models.CharField(_('name'), max_length=50)
    email = models.EmailField()
    message = models.TextField()
    resolved = models.BooleanField(_('resolved'), default=False)

    class Meta:
        verbose_name = _('Help Question')
        verbose_name_plural = _('Help Questions')

    def __unicode__(self):
        return self.name

class Slot(models.Model):
    title = models.CharField(_('slot'), max_length=20)
    start = models.DateTimeField(_('start time'))
    end = models.DateTimeField(_('end time'))
    question = models.ManyToManyField(Question)

    class Meta:
        verbose_name = _('Slot')
        verbose_name_plural = _('Slots')

    def __unicode__(self):
        return self.title

quriosity/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="theme-color" content="#999999" />
    <title>Quriosity</title>
    <link rel="shortcut icon" href="/static/favicon.ico">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Amatic+SC">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/css/material-kit.css" rel="stylesheet"/>
    <style>
    @font-face {
        font-family: titleFont;
        src: url('/static/font/title-font.ttf');
    }
    </style>
</head>
<body class="landing-page">
    <nav class="navbar navbar-success" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/quriosity/dashboard" style="font-family: titleFont;">Quriosity</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="btn btn-success" id="counter" style="font-size: 1.5em"></a></li>
                    <li><a class="btn btn-success" data-toggle="modal" data-target="#rulesModal">Rules</a></li>
                    <li><a class="btn btn-success" data-toggle="modal" data-target="#helpModal">Help</a></li>
                    <li><a class="btn btn-success" href="{% url 'details' %}">Profile Details</a></li>
                    <li><a class="btn btn-success" href="{% url 'logout' %}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="rulesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Rules</h4>
          </div>
          <div class="modal-body">
            <ul>
              <li>This quiz contains 15 question and you have 1 hour to complete it.</li>
              <li>Each question contains markings corresponding to it and Top 10% performing team will be selected for second round.</li>
              <li>Their will be no negative markings.</li>
              <li>For live updates regrding test stay connected to our <a href="https://www.facebook.com/events/978303445614068">facebook page</a></li>
              <li>Use should fill your <a href="/quriosity/details">profile details</a></li>
              <li>Their are two slots available for event, If you missed one you can change slot by contacting support.</li>
              <li>You can edit your answers during contest but they will be locked after end time of contest.</li>
              <li>During a contest contestants can ask questions to the contest jury via email <a href="mailto:quriosity@shilpiitbhu.org">quriosity@shilpiitbhu.org</a> . The questions may concern mistakes, ambiguous spots and inaccuracies in the statement.</li>
              <li>Any attempt to attack and disrupt server will be considered violation and will lead to disqualification.</li>
              <li>In case of any confilct, decision of <a href="www.shilpiitbhu.org">Shilp</a> team will be Final decision.</li>
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="helpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Help</h4>
          </div>
          <div class="modal-body">
            <ul>
              <li>If team members are taking contest from different location, make sure your answers doesn't confilct with others. You can always reload the page to see what the submitted answer is.</li>
              <li>If any unwanted error occured in portal contact <a href="mailto:quriosity@shipiitbhu.org">quriosity@shipiitbhu.org</a></li>
              <li>For any kind of changes to your team contact <a href="mailto:quriosity@shipiitbhu.org">quriosity@shipiitbhu.org</a></li>
              <li>For any quries and doubts contact <a href="mailto:quriosity@shipiitbhu.org">quriosity@shipiitbhu.org</a></li>
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
            
    {% block content %}
    {% endblock %}
</body>
<!--   Core JS Files   -->
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/material.min.js"></script>
<script src="/static/js/material-kit.js" type="text/javascript"></script>
{% block script %}
{% endblock %}
</html>

quriosity/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
    <div class="wrapper">
        <div class="container">
        <h5>Time increased by 15 min.</h5>
          {% csrf_token %}
          <div class="panel-group" id="accordion">
            {% for question in questions %}
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{forloop.counter}}">
                      {{question.title}}
                    </a>
                    <span class="score" style="float: right;">Score: {{question.score}}</span>
                  </h4>
                </div>
                <div id="collapse{{forloop.counter}}" class="panel-collapse collapse">
                  <div class="panel-body">
                    {{question.content | safe}}
                    <div class="row">
                      <div class="col-md-4">
                          <input type="text" class="form-control" id="ans-{{question.id}}" data-num="{{forloop.counter}}" placeholder="Answer" style="color: black;" maxlength="15">
                          <button class="btn btn-info btn-raised submit-q" id="{{question.id}}">Submit</button>
                          <p id="load-{{question.id}}" hidden>Submitting......</p>
                      </div>  
                    </div>
                  </div>
                </div>
              </div>
            {% empty %}
            <p>No questions for this round!!</p>
            {% endfor %}
          </div>
          <h5>Done before end time <button id="done" class="btn btn-success" id="">Press this</button>.</h5>
          <h5>During a contest contestants can ask questions to the contest jury via email <a href="mailto:quriosity@shilpiitbhu.org">quriosity@shilpiitbhu.org</a> . The questions may concern mistakes, ambiguous spots and inaccuracies in the statement.</h5>
          <h5>Incase of any error during contest try reloading your browser or contact support.</h5>
        </div>
    </div>
{% endblock %}

{% block script %}
<script src="/static/js/notify.min.js"></script>
<script>
  function getCSRF(){
      return document.getElementsByName('csrfmiddlewaretoken')[0].value;
  }

  function countdown(minutes) {
      var seconds = 60;
      var mins = minutes
      function tick() {
          var counter = document.getElementById("counter");
          var current_minutes = mins-1
          seconds--;
          counter.innerHTML = (current_minutes < 0 ? "0": current_minutes.toString()) + ":" + (seconds < 10 ? "0" : "") + String(seconds);
          if( seconds > 0 ) {
              setTimeout(tick, 1000);
          } else {
              if(mins > 1){
                  countdown(mins-1);           
              }
          }
      }
      tick();
  }

  setTimeout(function(){ window.location = "/quriosity/details"; }, ({{diff}})*1000);

  $(document).ready(function(){
    countdown(Math.floor({{diff}}/60));
    inputs = document.getElementsByTagName('input')
    inputs[1].value = {{team.response1}}
    inputs[2].value = {{team.response2}}
    inputs[3].value = {{team.response3}}
    inputs[4].value = {{team.response4}}
    inputs[5].value = {{team.response5}}
    inputs[6].value = {{team.response6}}
    inputs[7].value = {{team.response7}}
    inputs[8].value = {{team.response8}}
    inputs[9].value = {{team.response9}}
    inputs[10].value = {{team.response10}}
    inputs[11].value = {{team.response11}}
    inputs[12].value = {{team.response12}}
    inputs[13].value = {{team.response13}}
    inputs[14].value = {{team.response14}}
    inputs[15].value = {{team.response15}}
  });

  $("#done").click(function(){
    var p = confirm("Are you sure, you completed all question ??");
    if (p) {
      window.location = "/quriosity/details";
    }
  })

  $(".submit-q").click(function(){
    data = {
      csrfmiddlewaretoken: getCSRF(),
      qid: this.id,
      ans: $("#ans-"+this.id).val(),
      num: $("#ans-"+this.id).attr('data-num')
    }
    var i = this.id;
    $('#'+i).toggle();
    $('#load-'+i).toggle();
    $.ajax({
      url: '/quriosity/question/'+this.id+'/',
      type: 'POST',
      data: data,
      dataType: 'json',
      success: function(data){
        $('#'+i).toggle();
        $('#load-'+i).toggle();
        if (data.error){
          $.notify(data.msg, "error");
        } else {
          $.notify(data.msg, "info");
        }
      }
    });
  });
</script>
{% endblock %}

quriosity/templates/details.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="background-color: #eee">
<form method="post">
    {% csrf_token %}
    <h3>Members details</h3>
    {% for mem in members %}
    <div class="panel panel-success">
      <div class="panel-body">
        Member {{forloop.counter}} details
      </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} Name</label>
                <input type="text" class="form-control" value="{{mem.name}}" name="name{{forloop.counter}}" disabled>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} Email</label>
                <input type="email" class="form-control" value="{{mem.email}}" name="email{{forloop.counter}}" disabled>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} Phone</label>
                <input type="phone" class="form-control" value="{{mem.phone}}" name="phone{{forloop.counter}}" maxlength="13" required>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} College</label>
                <input type="text" class="form-control" value="{{mem.college}}" name="clg{{forloop.counter}}" maxlength="50" required>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} Year (1/2/3/4/5/None)</label>
                <input type="text" class="form-control" value="{{mem.year}}" name="year{{forloop.counter}}" maxlength="4" required>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group label-floating">
                <label class="control-label">Member {{forloop.counter}} Gender (M/F)</label>
                <input type="text" class="form-control" value="{{mem.gender}}" name="sex{{forloop.counter}}" maxlength="4" required>
            </div>
        </div>
    </div>
    <hr>
    {% empty %}
    <p>No members.</p>
    {% endfor %}
    <button class="btn btn-success btn-lg" type="submit">Submit Details</button>
</form>
</div>
{% endblock %}

quriosity/templates/responses.html
<table>
<tr>
    <th>team_id</th>
    <th>team_name</th>
    <th>question_id</th>
    <th>question_name</th>
    <th>response</th>
</tr>
{% for response in responses %}
<tr>
    <td>{{response.team.id}}</td>
    <td>{{response.team.name}}</td>
    <td>{{response.question.id}}</td>
    <td>{{response.question.title}}</td>
    <td>{{response.response}}</td>
</tr>
{% endfor %}
</table>

quriosity/templates/users.html
<table>
{% for user in users %}
<tr>
    <td>{{user.email}}</td>
    {% for team in user.team_set.all %}
        <td>{{team.name}}</td>
        <td>{{team.password}}</td>
        <td>{{team.slot}}</td>
    {% endfor %}
</tr>
{% endfor %}
</table>

quriosity/templates/waiting.html
{% extends "base.html" %}
{% block content %}
    <link rel="stylesheet" href="/static/css/flipclock.css">
    <div class="container text-center" style="margin: auto">
        {% if diff >= 0 %}
        <h1 class="title">Slot {{team.slot}} starts in </h1>
        <div class="timer"></div>
        <h2>Please read the rules and help section for more details.</h2>
        {% else %}
        <h1 class="title">Round {{team.slot}} is over.</h1>
        <h5>Result will be declared soon and will be mailed to you.</h5>
        <h5>For further details contact us at <a href="mailto:quriosity@shilpiitbhu.org">quriosity@shilpiitbhu.org</a>.</h5>
        <h3>Make sure you completed your <a href="/quriosity/details/">profile details</a> to be eligible for Second Round</h3>
        {% endif %}
    </div>    
{% endblock %}

{% block script %}
<script src="/static/js/flipclock.min.js"></script>
<script>
    $(document).ready(function(){
        if ({{diff}} > 0){
            var clock = $('.timer').FlipClock({{diff}}, {
                clockFace: 'DailyCounter',
                countdown: true
            });

            setTimeout(function(){ location.reload(); }, ({{diff}}+2)*1000);
        }
    });
</script>
{% endblock %}

quriosity/templates/winners.html
<table>
    {% for winner in winners %}
    <tr>
        <td>{{winner.id}}</td>
        <td>{{winner.name}}</td>
        <td>{{score}}</td>
        {% for member in winner.members.all %}
            <td>{{member.name}}</td>
            <td>{{member.email}}</td>
            <td>{{member.phone}}</td>
            <td>{{member.college}}</td>
            <td>{{member.gender}}</td>
            <td>{{member.year}}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>